-- 확인예제(10:41분 실행)  family를 계층구조로 출력
-- 출력형식 : level role(계층구조 공백처리), 이름
SELECT LEVEL, LPAD('└', LEVEL*5)||ROLE01 "역할", NAME 
FROM FAMILY START  WITH PARENTNUMID=0 CONNECT BY PRIOR NUMID=PARENTNUMID;


-- 확인예제(12:51분 실행) EMP테이블의 복사본 EMP11 생성하고,
--         JOB(직책)이 PRESIDENT에 있는 SAL과 DEPTNO를 JOB이 CLERK에 있는 데이터로 UPDATE하세요
CREATE TABLE EMP11 AS SELECT * FROM EMP;
UPDATE EMP11 
	SET (SAL, DEPTNO) = (SELECT SAL, DEPTNO FROM EMP11 WHERE JOB='PRESIDENT')
	WHERE JOB='CLERK';


/***
확인예제(15:30분 실행) : emp의 복사테이블 emp03을 생성하고 
emp에서 부서번호(deptno)가 30인 데이터를 emp04로 복사테이블 만들기
	emp04의 hiredate를 오늘날(SYSDATE)로 UPDATE처리..
	emp04에 7370 '원더걸' 'superman' 7839 sysdate 6000 400 40데이터 입력
***/
CREATE TABLE EMP03 AS SELECT * FROM EMP;
CREATE TABLE EMP04 AS SELECT * FROM EMP WHERE DEPTNO=30;
UPDATE EMP04 SET HIREDATE=SYSDATE;
INSERT INTO EMP04 VALUES (7370, '원더걸','SUPERMAN', 7839, SYSDATE, 6000,400,40);
MERGE INTO EMP03
	USING EMP04
	ON (EMP03.EMPNO = EMP04.EMPNO)
	WHEN MATCHED THEN
		UPDATE SET
		EMP03.HIREDATE = EMP04.HIREDATE
	WHEN NOT MATCHED THEN
		INSERT VALUES (EMP04.EMPNO, EMP04.ENAME, EMP04.JOB, EMP04.MGR,
		EMP04.HIREDATE, EMP04.SAL, EMP04.COMM, EMP04.DEPTNO);
SELECT * FROM EMP03;
