/*** 숙제
	EMP03 복사테이블 생성
	1. 입력 : EMPNO의 가장 작은 수보다 -1, MGR:CLARK의 MGR입력, SAL 평균연봉, COMM:전체 COMM의 합계
	2. 수정 : ENAME : '신길동', JOB은 'SUPERMAN', HIREDATE는 최근에 입사일+1
***/
CREATE TABLE EMP03 AS SELECT * FROM EMP; 
INSERT INTO EMP03 (EMPNO, MGR, SAL, COMM) 
	VALUES((SELECT MIN(EMPNO)-1 FROM EMP), 
	(SELECT MGR FROM EMP WHERE ENAME='CLARK'), 
	(SELECT AVG(SAL) FROM EMP), 
	(SELECT AVG(NVL(COMM,0)) FROM EMP03));
UPDATE EMP03 
	SET ENAME='신길동', 
		JOB = 'SUPERMAN', 
		HIREDATE=(SELECT MAX(HIREDATE)+1 FROM EMP) 
	WHERE EMPNO=7368;
SELECT * FROM EMP03 WHERE EMPNO=7368;

/* 과제 :
	login하는 화면을 만들고 id와 password를 체크하고, 다음 화면에서
	"id @@@님 환영합니다. 남은 point는 @@@ 입니다"라는 내용이 나타난다고 한다.
	이에 필요로 하는 테이블과 테이블 구조를 만드세요
*/
CREATE TABLE MEMBER (
	ID VARCHAR2(20) PRIMARY KEY,
	PASSWORD VARCHAR2(20) NOT NULL, 
	NAME VARCHAR2(20) NOT NULL, 
	POINT NUMBER DEFAULT 0);
SELECT * FROM MEMBER;

/***
3시45분 숙제 : 참조키 관계에 있는 테이블 구성하기
	메인테이블 STUDENT_MAIN(ID,PASS,NAME); 아이디, 패스워드, 이름
	서브테이블 STUDENT_POINT(ID, SUBJECT, POINT); 아이디, 과목, 점수
***/
CREATE TABLE STUDENT_MAIN(
	ID VARCHAR2(20) PRIMARY KEY,
	PASS VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20) NOT NULL
);
CREATE TABLE STUDENT_POINT(
	ID VARCHAR2(20) REFERENCES STUDENT_MAIN(ID),
	SUBJECT VARCHAR2(20),
	POINT NUMBER(3)
);